name: OpenElections
title: OpenElections
highlighter: rouge
baseurl: ''
include: [news]
exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - vendor
destination: _site
sass:
    sass_dir: _sass
